// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: tpre.proto

package tpre

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Re-encryption request from a reader (SDK client).
//
// The reader must have already completed a Spark transfer to the author
// as proof of payment.
type ReEncryptionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full ECIES ciphertext: sealed content key encrypted to the
	// federation's threshold public key.
	// Format: [65-byte ephemeral pubkey] [16-byte nonce] [16-byte tag] [encrypted data]
	SealedContentKey []byte `protobuf:"bytes,1,opt,name=sealed_content_key,json=sealedContentKey,proto3" json:"sealed_content_key,omitempty"`
	// The reader's secp256k1 public key (33 or 65 bytes).
	// The content key will be re-encrypted to this key.
	// This SHOULD be the reader's financial (wallet) public key for DRM purposes.
	ReaderPublicKey []byte `protobuf:"bytes,2,opt,name=reader_public_key,json=readerPublicKey,proto3" json:"reader_public_key,omitempty"`
	// The author's identity public key (33 bytes).
	// Used to verify the payment was directed to the correct author.
	AuthorPublicKey []byte `protobuf:"bytes,3,opt,name=author_public_key,json=authorPublicKey,proto3" json:"author_public_key,omitempty"`
	// The expected payment amount in satoshis.
	PaymentAmountSats uint64 `protobuf:"varint,4,opt,name=payment_amount_sats,json=paymentAmountSats,proto3" json:"payment_amount_sats,omitempty"`
	// The Spark transfer ID proving the reader paid the author.
	TransferId string `protobuf:"bytes,5,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	// Content identifier (e.g., SHA-256 hash of the post metadata).
	// Used for idempotency: the same reader can only re-encrypt once per post.
	PostId        []byte `protobuf:"bytes,6,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptionRequest) Reset() {
	*x = ReEncryptionRequest{}
	mi := &file_tpre_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptionRequest) ProtoMessage() {}

func (x *ReEncryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpre_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptionRequest.ProtoReflect.Descriptor instead.
func (*ReEncryptionRequest) Descriptor() ([]byte, []int) {
	return file_tpre_proto_rawDescGZIP(), []int{0}
}

func (x *ReEncryptionRequest) GetSealedContentKey() []byte {
	if x != nil {
		return x.SealedContentKey
	}
	return nil
}

func (x *ReEncryptionRequest) GetReaderPublicKey() []byte {
	if x != nil {
		return x.ReaderPublicKey
	}
	return nil
}

func (x *ReEncryptionRequest) GetAuthorPublicKey() []byte {
	if x != nil {
		return x.AuthorPublicKey
	}
	return nil
}

func (x *ReEncryptionRequest) GetPaymentAmountSats() uint64 {
	if x != nil {
		return x.PaymentAmountSats
	}
	return 0
}

func (x *ReEncryptionRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ReEncryptionRequest) GetPostId() []byte {
	if x != nil {
		return x.PostId
	}
	return nil
}

// Re-encryption response to the reader.
//
// Contains the content key re-encrypted to the reader's public key.
type ReEncryptionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content key re-encrypted as ECIES ciphertext sealed to reader_public_key.
	ReEncryptedKey []byte `protobuf:"bytes,1,opt,name=re_encrypted_key,json=reEncryptedKey,proto3" json:"re_encrypted_key,omitempty"`
	// The post_id echoed back for correlation.
	PostId []byte `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	// The decrypted content key (plaintext hex). For PoC, allows direct delivery
	// without requiring ECIES decrypt on the client side.
	ContentKey    []byte `protobuf:"bytes,3,opt,name=content_key,json=contentKey,proto3" json:"content_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptionResponse) Reset() {
	*x = ReEncryptionResponse{}
	mi := &file_tpre_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptionResponse) ProtoMessage() {}

func (x *ReEncryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpre_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptionResponse.ProtoReflect.Descriptor instead.
func (*ReEncryptionResponse) Descriptor() ([]byte, []int) {
	return file_tpre_proto_rawDescGZIP(), []int{1}
}

func (x *ReEncryptionResponse) GetReEncryptedKey() []byte {
	if x != nil {
		return x.ReEncryptedKey
	}
	return nil
}

func (x *ReEncryptionResponse) GetPostId() []byte {
	if x != nil {
		return x.PostId
	}
	return nil
}

func (x *ReEncryptionResponse) GetContentKey() []byte {
	if x != nil {
		return x.ContentKey
	}
	return nil
}

// Internal: partial ECDH share request between operators.
//
// The coordinator operator sends this to each peer operator. The peer
// forwards it to its local FROST signer.
type PartialEcdhShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for correlation across operators.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The 65-byte uncompressed ephemeral public key from the ECIES ciphertext.
	EphemeralPublicKey []byte `protobuf:"bytes,2,opt,name=ephemeral_public_key,json=ephemeralPublicKey,proto3" json:"ephemeral_public_key,omitempty"`
	// The signing keyshare ID to use for the partial ECDH.
	// This identifies which FROST key share the signer should use.
	KeyshareId    string `protobuf:"bytes,3,opt,name=keyshare_id,json=keyshareId,proto3" json:"keyshare_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialEcdhShareRequest) Reset() {
	*x = PartialEcdhShareRequest{}
	mi := &file_tpre_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialEcdhShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialEcdhShareRequest) ProtoMessage() {}

func (x *PartialEcdhShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tpre_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialEcdhShareRequest.ProtoReflect.Descriptor instead.
func (*PartialEcdhShareRequest) Descriptor() ([]byte, []int) {
	return file_tpre_proto_rawDescGZIP(), []int{2}
}

func (x *PartialEcdhShareRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PartialEcdhShareRequest) GetEphemeralPublicKey() []byte {
	if x != nil {
		return x.EphemeralPublicKey
	}
	return nil
}

func (x *PartialEcdhShareRequest) GetKeyshareId() string {
	if x != nil {
		return x.KeyshareId
	}
	return ""
}

// Internal: partial ECDH share response from a peer operator.
type PartialEcdhShareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The 65-byte uncompressed partial ECDH point: S_i = key_share_i * R.
	PartialEcdhPoint []byte `protobuf:"bytes,1,opt,name=partial_ecdh_point,json=partialEcdhPoint,proto3" json:"partial_ecdh_point,omitempty"`
	// The operator's identifier (for Lagrange interpolation).
	OperatorIdentifier string `protobuf:"bytes,2,opt,name=operator_identifier,json=operatorIdentifier,proto3" json:"operator_identifier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PartialEcdhShareResponse) Reset() {
	*x = PartialEcdhShareResponse{}
	mi := &file_tpre_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialEcdhShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialEcdhShareResponse) ProtoMessage() {}

func (x *PartialEcdhShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tpre_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialEcdhShareResponse.ProtoReflect.Descriptor instead.
func (*PartialEcdhShareResponse) Descriptor() ([]byte, []int) {
	return file_tpre_proto_rawDescGZIP(), []int{3}
}

func (x *PartialEcdhShareResponse) GetPartialEcdhPoint() []byte {
	if x != nil {
		return x.PartialEcdhPoint
	}
	return nil
}

func (x *PartialEcdhShareResponse) GetOperatorIdentifier() string {
	if x != nil {
		return x.OperatorIdentifier
	}
	return ""
}

var File_tpre_proto protoreflect.FileDescriptor

const file_tpre_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tpre.proto\x12\x04tpre\"\x85\x02\n" +
	"\x13ReEncryptionRequest\x12,\n" +
	"\x12sealed_content_key\x18\x01 \x01(\fR\x10sealedContentKey\x12*\n" +
	"\x11reader_public_key\x18\x02 \x01(\fR\x0freaderPublicKey\x12*\n" +
	"\x11author_public_key\x18\x03 \x01(\fR\x0fauthorPublicKey\x12.\n" +
	"\x13payment_amount_sats\x18\x04 \x01(\x04R\x11paymentAmountSats\x12\x1f\n" +
	"\vtransfer_id\x18\x05 \x01(\tR\n" +
	"transferId\x12\x17\n" +
	"\apost_id\x18\x06 \x01(\fR\x06postId\"z\n" +
	"\x14ReEncryptionResponse\x12(\n" +
	"\x10re_encrypted_key\x18\x01 \x01(\fR\x0ereEncryptedKey\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\fR\x06postId\x12\x1f\n" +
	"\vcontent_key\x18\x03 \x01(\fR\n" +
	"contentKey\"\x8b\x01\n" +
	"\x17PartialEcdhShareRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\x14ephemeral_public_key\x18\x02 \x01(\fR\x12ephemeralPublicKey\x12\x1f\n" +
	"\vkeyshare_id\x18\x03 \x01(\tR\n" +
	"keyshareId\"y\n" +
	"\x18PartialEcdhShareResponse\x12,\n" +
	"\x12partial_ecdh_point\x18\x01 \x01(\fR\x10partialEcdhPoint\x12/\n" +
	"\x13operator_identifier\x18\x02 \x01(\tR\x12operatorIdentifier2\xba\x01\n" +
	"\vTpreService\x12P\n" +
	"\x15request_re_encryption\x12\x19.tpre.ReEncryptionRequest\x1a\x1a.tpre.ReEncryptionResponse\"\x00\x12Y\n" +
	"\x16get_partial_ecdh_share\x12\x1d.tpre.PartialEcdhShareRequest\x1a\x1e.tpre.PartialEcdhShareResponse\"\x00B+Z)github.com/lightsparkdev/spark/proto/tpreb\x06proto3"

var (
	file_tpre_proto_rawDescOnce sync.Once
	file_tpre_proto_rawDescData []byte
)

func file_tpre_proto_rawDescGZIP() []byte {
	file_tpre_proto_rawDescOnce.Do(func() {
		file_tpre_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tpre_proto_rawDesc), len(file_tpre_proto_rawDesc)))
	})
	return file_tpre_proto_rawDescData
}

var file_tpre_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tpre_proto_goTypes = []any{
	(*ReEncryptionRequest)(nil),      // 0: tpre.ReEncryptionRequest
	(*ReEncryptionResponse)(nil),     // 1: tpre.ReEncryptionResponse
	(*PartialEcdhShareRequest)(nil),  // 2: tpre.PartialEcdhShareRequest
	(*PartialEcdhShareResponse)(nil), // 3: tpre.PartialEcdhShareResponse
}
var file_tpre_proto_depIdxs = []int32{
	0, // 0: tpre.TpreService.request_re_encryption:input_type -> tpre.ReEncryptionRequest
	2, // 1: tpre.TpreService.get_partial_ecdh_share:input_type -> tpre.PartialEcdhShareRequest
	1, // 2: tpre.TpreService.request_re_encryption:output_type -> tpre.ReEncryptionResponse
	3, // 3: tpre.TpreService.get_partial_ecdh_share:output_type -> tpre.PartialEcdhShareResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tpre_proto_init() }
func file_tpre_proto_init() {
	if File_tpre_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tpre_proto_rawDesc), len(file_tpre_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tpre_proto_goTypes,
		DependencyIndexes: file_tpre_proto_depIdxs,
		MessageInfos:      file_tpre_proto_msgTypes,
	}.Build()
	File_tpre_proto = out.File
	file_tpre_proto_goTypes = nil
	file_tpre_proto_depIdxs = nil
}
