// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: tpre.proto

package tpre

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReEncryptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReEncryptionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReEncryptionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReEncryptionRequestMultiError, or nil if none found.
func (m *ReEncryptionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReEncryptionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SealedContentKey

	// no validation rules for ReaderPublicKey

	// no validation rules for AuthorPublicKey

	// no validation rules for PaymentAmountSats

	// no validation rules for TransferId

	// no validation rules for PostId

	if len(errors) > 0 {
		return ReEncryptionRequestMultiError(errors)
	}

	return nil
}

// ReEncryptionRequestMultiError is an error wrapping multiple validation
// errors returned by ReEncryptionRequest.ValidateAll() if the designated
// constraints aren't met.
type ReEncryptionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReEncryptionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReEncryptionRequestMultiError) AllErrors() []error { return m }

// ReEncryptionRequestValidationError is the validation error returned by
// ReEncryptionRequest.Validate if the designated constraints aren't met.
type ReEncryptionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReEncryptionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReEncryptionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReEncryptionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReEncryptionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReEncryptionRequestValidationError) ErrorName() string {
	return "ReEncryptionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReEncryptionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReEncryptionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReEncryptionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReEncryptionRequestValidationError{}

// Validate checks the field values on ReEncryptionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReEncryptionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReEncryptionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReEncryptionResponseMultiError, or nil if none found.
func (m *ReEncryptionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReEncryptionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReEncryptedKey

	// no validation rules for PostId

	if len(errors) > 0 {
		return ReEncryptionResponseMultiError(errors)
	}

	return nil
}

// ReEncryptionResponseMultiError is an error wrapping multiple validation
// errors returned by ReEncryptionResponse.ValidateAll() if the designated
// constraints aren't met.
type ReEncryptionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReEncryptionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReEncryptionResponseMultiError) AllErrors() []error { return m }

// ReEncryptionResponseValidationError is the validation error returned by
// ReEncryptionResponse.Validate if the designated constraints aren't met.
type ReEncryptionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReEncryptionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReEncryptionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReEncryptionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReEncryptionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReEncryptionResponseValidationError) ErrorName() string {
	return "ReEncryptionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReEncryptionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReEncryptionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReEncryptionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReEncryptionResponseValidationError{}

// Validate checks the field values on PartialEcdhShareRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PartialEcdhShareRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartialEcdhShareRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PartialEcdhShareRequestMultiError, or nil if none found.
func (m *PartialEcdhShareRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PartialEcdhShareRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	// no validation rules for EphemeralPublicKey

	// no validation rules for KeyshareId

	if len(errors) > 0 {
		return PartialEcdhShareRequestMultiError(errors)
	}

	return nil
}

// PartialEcdhShareRequestMultiError is an error wrapping multiple validation
// errors returned by PartialEcdhShareRequest.ValidateAll() if the designated
// constraints aren't met.
type PartialEcdhShareRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartialEcdhShareRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartialEcdhShareRequestMultiError) AllErrors() []error { return m }

// PartialEcdhShareRequestValidationError is the validation error returned by
// PartialEcdhShareRequest.Validate if the designated constraints aren't met.
type PartialEcdhShareRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartialEcdhShareRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartialEcdhShareRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartialEcdhShareRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartialEcdhShareRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartialEcdhShareRequestValidationError) ErrorName() string {
	return "PartialEcdhShareRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PartialEcdhShareRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartialEcdhShareRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartialEcdhShareRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartialEcdhShareRequestValidationError{}

// Validate checks the field values on PartialEcdhShareResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PartialEcdhShareResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PartialEcdhShareResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PartialEcdhShareResponseMultiError, or nil if none found.
func (m *PartialEcdhShareResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PartialEcdhShareResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PartialEcdhPoint

	// no validation rules for OperatorIdentifier

	if len(errors) > 0 {
		return PartialEcdhShareResponseMultiError(errors)
	}

	return nil
}

// PartialEcdhShareResponseMultiError is an error wrapping multiple validation
// errors returned by PartialEcdhShareResponse.ValidateAll() if the designated
// constraints aren't met.
type PartialEcdhShareResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PartialEcdhShareResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PartialEcdhShareResponseMultiError) AllErrors() []error { return m }

// PartialEcdhShareResponseValidationError is the validation error returned by
// PartialEcdhShareResponse.Validate if the designated constraints aren't met.
type PartialEcdhShareResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PartialEcdhShareResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PartialEcdhShareResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PartialEcdhShareResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PartialEcdhShareResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PartialEcdhShareResponseValidationError) ErrorName() string {
	return "PartialEcdhShareResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PartialEcdhShareResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPartialEcdhShareResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PartialEcdhShareResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PartialEcdhShareResponseValidationError{}
