// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: tpre.proto

package tpre

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TpreService_RequestReEncryption_FullMethodName = "/tpre.TpreService/request_re_encryption"
	TpreService_GetPartialEcdhShare_FullMethodName = "/tpre.TpreService/get_partial_ecdh_share"
)

// TpreServiceClient is the client API for TpreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Threshold Proxy Re-Encryption Service.
//
// Enables payment-gated content key re-encryption. An author encrypts a
// symmetric content key to the federation's threshold public key at publish
// time. When a reader pays (via Spark statechain transfer), the federation
// threshold-decrypts the content key and re-encrypts it to the reader's
// public key.
//
// This service runs on each Spark operator and is accessible to SDK clients.
type TpreServiceClient interface {
	// Request re-encryption of a sealed content key after proving payment.
	// The coordinator operator collects partial ECDH shares from peer operators'
	// FROST signers, reconstructs the shared secret, decrypts the content key,
	// and re-encrypts it to the reader's public key.
	RequestReEncryption(ctx context.Context, in *ReEncryptionRequest, opts ...grpc.CallOption) (*ReEncryptionResponse, error)
	// Internal: operator-to-operator request for a partial ECDH share.
	// Called by the coordinator operator on peer operators during re-encryption.
	GetPartialEcdhShare(ctx context.Context, in *PartialEcdhShareRequest, opts ...grpc.CallOption) (*PartialEcdhShareResponse, error)
}

type tpreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTpreServiceClient(cc grpc.ClientConnInterface) TpreServiceClient {
	return &tpreServiceClient{cc}
}

func (c *tpreServiceClient) RequestReEncryption(ctx context.Context, in *ReEncryptionRequest, opts ...grpc.CallOption) (*ReEncryptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReEncryptionResponse)
	err := c.cc.Invoke(ctx, TpreService_RequestReEncryption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tpreServiceClient) GetPartialEcdhShare(ctx context.Context, in *PartialEcdhShareRequest, opts ...grpc.CallOption) (*PartialEcdhShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartialEcdhShareResponse)
	err := c.cc.Invoke(ctx, TpreService_GetPartialEcdhShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TpreServiceServer is the server API for TpreService service.
// All implementations must embed UnimplementedTpreServiceServer
// for forward compatibility.
//
// Threshold Proxy Re-Encryption Service.
//
// Enables payment-gated content key re-encryption. An author encrypts a
// symmetric content key to the federation's threshold public key at publish
// time. When a reader pays (via Spark statechain transfer), the federation
// threshold-decrypts the content key and re-encrypts it to the reader's
// public key.
//
// This service runs on each Spark operator and is accessible to SDK clients.
type TpreServiceServer interface {
	// Request re-encryption of a sealed content key after proving payment.
	// The coordinator operator collects partial ECDH shares from peer operators'
	// FROST signers, reconstructs the shared secret, decrypts the content key,
	// and re-encrypts it to the reader's public key.
	RequestReEncryption(context.Context, *ReEncryptionRequest) (*ReEncryptionResponse, error)
	// Internal: operator-to-operator request for a partial ECDH share.
	// Called by the coordinator operator on peer operators during re-encryption.
	GetPartialEcdhShare(context.Context, *PartialEcdhShareRequest) (*PartialEcdhShareResponse, error)
	mustEmbedUnimplementedTpreServiceServer()
}

// UnimplementedTpreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTpreServiceServer struct{}

func (UnimplementedTpreServiceServer) RequestReEncryption(context.Context, *ReEncryptionRequest) (*ReEncryptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestReEncryption not implemented")
}
func (UnimplementedTpreServiceServer) GetPartialEcdhShare(context.Context, *PartialEcdhShareRequest) (*PartialEcdhShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartialEcdhShare not implemented")
}
func (UnimplementedTpreServiceServer) mustEmbedUnimplementedTpreServiceServer() {}
func (UnimplementedTpreServiceServer) testEmbeddedByValue()                     {}

// UnsafeTpreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TpreServiceServer will
// result in compilation errors.
type UnsafeTpreServiceServer interface {
	mustEmbedUnimplementedTpreServiceServer()
}

func RegisterTpreServiceServer(s grpc.ServiceRegistrar, srv TpreServiceServer) {
	// If the following call panics, it indicates UnimplementedTpreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TpreService_ServiceDesc, srv)
}

func _TpreService_RequestReEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReEncryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpreServiceServer).RequestReEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TpreService_RequestReEncryption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpreServiceServer).RequestReEncryption(ctx, req.(*ReEncryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TpreService_GetPartialEcdhShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartialEcdhShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TpreServiceServer).GetPartialEcdhShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TpreService_GetPartialEcdhShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TpreServiceServer).GetPartialEcdhShare(ctx, req.(*PartialEcdhShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TpreService_ServiceDesc is the grpc.ServiceDesc for TpreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TpreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tpre.TpreService",
	HandlerType: (*TpreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request_re_encryption",
			Handler:    _TpreService_RequestReEncryption_Handler,
		},
		{
			MethodName: "get_partial_ecdh_share",
			Handler:    _TpreService_GetPartialEcdhShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tpre.proto",
}
